services:
  django:
    build: ./backend
    expose:
      - "8000"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
      - logs_volume:/logs
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn shortner.wsgi:application --bind 0.0.0.0:8000
      "

    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health/').getcode()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  worker:
    build: ./backend
    command: celery -A shortner worker -l INFO
    networks:
      - backend_network
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy

  beat:
    build: ./backend
    command: celery -A shortner beat -l INFO -S django
    networks:
      - backend_network
    depends_on:
      redis:
        condition: service_healthy
      database:
        condition: service_healthy

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    restart: unless-stopped
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  frontend:
    build: ./frontend
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
  
  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      django:
        condition: service_healthy
    volumes:
      - static_volume:/app/staticfiles:ro  
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ping/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  
  redis:
    build: ./redis
    restart: unless-stopped
    expose:
      - "6379"
    volumes:
      - ./redis_data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s
    networks:
      - backend_network

  s3:
    image: minio/minio:latest
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER: ${MINIO_BROWSER}
      MINIO_CONSOLE_UI_DISABLED: ${MINIO_CONSOLE_UI_DISABLED}

    command: server --address ":9000" --console-address ":9001" /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    
    # Why not expose? ref the decisions_made file
    ports:  
      - "9000:9000"
      - "9001:9001"
    volumes:
      - s3_data:/data

    networks:
      - backend_network
  
  # For creating first time setup of users, bucket...etc
  s3-setup:
    image: minio/mc:latest
    container_name: s3-setup
    entrypoint: ["/bin/sh"] 
    volumes:
      - ./s3/setup/01-bucket-creation-and-user-addition.sh:/usr/local/bin/01-bucket-creation-and-user-addition.sh
    environment:
      MINIO_SERVER: ${MC_HOST_local}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      USER_NAME: ${AWS_ACCESS_KEY_ID}
      USER_SECRET: ${AWS_SECRET_ACCESS_KEY}
      BUCKET_NAME: ${AWS_STORAGE_BUCKET_NAME}
    command: ["/usr/local/bin/01-bucket-creation-and-user-addition.sh"]
    restart: "no"
    depends_on:
      s3:
        condition: service_healthy
    networks:
      - backend_network
    

volumes:
  mysql_data:
  static_volume:
  logs_volume:
  redis_data:
  s3_data:

networks:
  backend_network:
    driver: bridge  
    
